### ISSUE TITLE
Error with 0.11.7

### ISSUE THREAD

**Issue by majoshi1** [docker-library/ghost#64]
Getting following error with 0.11.7. Works fine with 0.11.5.

```
$ docker run --name xyz-blog -v /data/xyz:/var/lib/ghost ghost
722...
$ docker logs 722...
module.js:327
    throw err;
    ^

Error: Cannot find module 'ansi'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/progress-bar.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by yosifkit** [comment]
I am unable to reproduce.  I am not sure what is already in your `/data/xyz` directory.  Can you give any more information on what is already in this directory or what other steps might lead to this bug?  I thought maybe there was an issue when starting with data from `0.11.5` and moving to `0.11.7` but I didn't see anything:

```console
$ mkdir ghost
$ docker run -it --rm --name ghost -v $PWD/ghost:/var/lib/ghost ghost:0.11.5
Unable to find image 'ghost:0.11.5' locally
0.11.5: Pulling from library/ghost
693502eb7dfb: Already exists 
081cd4bfd521: Pull complete 
ccdac388e8ea: Pull complete 
d2d7bf5eae4b: Pull complete 
11bf59480dfa: Pull complete 
c61f29fdb690: Pull complete 
103bbdd07369: Pull complete 
70e8925653bb: Pull complete 
b5e60c6d76f0: Pull complete 
a5f2a73f7854: Pull complete 
8b104bb78387: Pull complete 
04a173af8ae2: Pull complete 
Digest: sha256:e903bcb7c8771a718a8eb86911d7e94458809d3fd5bbb442f2bf761fce98b7f6
Status: Downloaded newer image for ghost:0.11.5
npm info it worked if it ends with ok
npm info using npm@2.15.11
npm info using node@v4.8.0
npm info prestart ghost@0.11.5
npm info start ghost@0.11.5

> ghost@0.11.5 start /usr/src/ghost
> node index

WARNING: Ghost is attempting to use a direct method to send email. 
It is recommended that you explicitly configure an email service.
Help and documentation can be found at http://support.ghost.org/mail.

Migrations: Creating tables...
Migrations: Creating table: posts
Migrations: Creating table: users
Migrations: Creating table: roles
Migrations: Creating table: roles_users
Migrations: Creating table: permissions
Migrations: Creating table: permissions_users
Migrations: Creating table: permissions_roles
Migrations: Creating table: permissions_apps
Migrations: Creating table: settings
Migrations: Creating table: tags
Migrations: Creating table: posts_tags
Migrations: Creating table: apps
Migrations: Creating table: app_settings
Migrations: Creating table: app_fields
Migrations: Creating table: clients
Migrations: Creating table: client_trusted_domains
Migrations: Creating table: accesstokens
Migrations: Creating table: refreshtokens
Migrations: Creating table: subscribers
Migrations: Running fixture populations
Migrations: Creating owner
Ghost is running in development... 
Listening on 0.0.0.0:2368 
Url configured as: http://localhost:2368 
Ctrl+C to shut down
^C
Ghost has shut down

Ghost was running for a few seconds
npm info poststart ghost@0.11.5
npm info ok 
$ docker run -it --rm --name ghost -v $PWD/ghost:/var/lib/ghost ghost:0.11.7
npm info it worked if it ends with ok
npm info using npm@2.15.11
npm info using node@v4.8.0
npm info prestart ghost@0.11.7
npm info start ghost@0.11.7

> ghost@0.11.7 start /usr/src/ghost
> node index

WARNING: Ghost is attempting to use a direct method to send email. 
It is recommended that you explicitly configure an email service.
Help and documentation can be found at http://support.ghost.org/mail.

Ghost is running in development... 
Listening on 0.0.0.0:2368 
Url configured as: http://localhost:2368 
Ctrl+C to shut down
^C
Ghost has shut down
Ghost was running for 2 minutes
npm info poststart ghost@0.11.7
npm info ok 
```
